"""First migration

Revision ID: 288c9cd348ac
Revises: 
Create Date: 2023-06-01 22:57:47.872427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288c9cd348ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('zip', sa.String(length=5), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state_name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zip')
    )
    op.create_table('car',
    sa.Column('car_code', sa.String(length=5), nullable=False),
    sa.Column('current_location', sa.String(length=5), nullable=False),
    sa.Column('capacity_car', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_location'], ['location.zip'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_code')
    )
    op.create_table('shipment',
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('shipment_weight', sa.Integer(), nullable=False),
    sa.Column('location_pickup', sa.String(length=5), nullable=False),
    sa.Column('location_delivery', sa.String(length=5), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_delivery'], ['location.zip'], ),
    sa.ForeignKeyConstraint(['location_pickup'], ['location.zip'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment')
    op.drop_table('car')
    op.drop_table('location')
    # ### end Alembic commands ###
